# Generated by Django 6.0 on 2026-01-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('year_code', models.CharField(help_text='Format: "24-25" for 2024-2025 academic year', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(help_text='July 1 of start year')),
                ('end_date', models.DateField(help_text='June 30 of end year')),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-year_code'],
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('email', models.EmailField(help_text='Primary identifier - must match survey submissions', max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('assistant', 'Assistant Professor'), ('associate', 'Associate Professor'), ('professor', 'Professor')], default='', max_length=20)),
                ('contract_type', models.CharField(blank=True, choices=[('academic', 'Academic'), ('clinical', 'Clinical'), ('early_career', 'Early Career (Yrs 1-3)')], default='', max_length=20)),
                ('division', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ccc_member', models.BooleanField(default=False, help_text='Clinical Competency Committee member (1000 pts, persists year-to-year)', verbose_name='CCC Member')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, help_text='Username if authentication is enabled', max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('faculty_count', models.IntegerField(default=0)),
                ('activity_count', models.IntegerField(default=0)),
                ('unmatched_emails', models.JSONField(default=list, help_text='List of email addresses not found in roster')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_imports', to='reports_app.academicyear')),
            ],
            options={
                'verbose_name': 'Survey Import',
                'verbose_name_plural': 'Survey Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_innovations', models.BooleanField(default=False, help_text='Completed 80%+ of assigned evaluations (2,000 pts)', verbose_name='New Innovations (80%+)')),
                ('mytip_winner', models.BooleanField(default=False, help_text='MyTIP Report Winner for the quarter (250 pts)', verbose_name='MyTIP Report Winner')),
                ('mytip_count', models.PositiveIntegerField(default=0, help_text='Number of MyTIP evaluations (25 pts each, max 20)', verbose_name='MyTIP Report Count')),
                ('teaching_top_25', models.BooleanField(default=False, help_text='Teaching evaluation in top 25% (2,500 pts)', verbose_name='Top 25%')),
                ('teaching_65_25', models.BooleanField(default=False, help_text='Teaching evaluation in 65-25% range (1,000 pts)', verbose_name='Top 65-25%')),
                ('teacher_of_year', models.BooleanField(default=False, help_text='Teacher of the Year award (7,500 pts)', verbose_name='Teacher of the Year')),
                ('honorable_mention', models.BooleanField(default=False, help_text='Honorable Mention for teaching (5,000 pts)', verbose_name='Honorable Mention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_data', to='reports_app.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmental_data', to='reports_app.facultymember')),
            ],
            options={
                'verbose_name': 'Departmental Data',
                'verbose_name_plural': 'Departmental Data',
                'ordering': ['faculty__last_name', 'faculty__first_name'],
                'unique_together': {('faculty', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FacultySurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarters_reported', models.JSONField(default=list, help_text='List of quarters submitted: ["Q1-Q2", "Q3", "Q4"]')),
                ('has_incomplete', models.BooleanField(default=False, help_text='True if any submission was marked incomplete')),
                ('citizenship_points', models.IntegerField(default=0)),
                ('education_points', models.IntegerField(default=0)),
                ('research_points', models.IntegerField(default=0)),
                ('leadership_points', models.IntegerField(default=0)),
                ('content_expert_points', models.IntegerField(default=0)),
                ('survey_total_points', models.IntegerField(default=0)),
                ('activities_json', models.JSONField(default=dict, help_text='Complete activity data structure from parser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_data', to='reports_app.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_data', to='reports_app.facultymember')),
                ('survey_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_data', to='reports_app.surveyimport')),
            ],
            options={
                'verbose_name': 'Faculty Survey Data',
                'verbose_name_plural': 'Faculty Survey Data',
                'ordering': ['faculty__last_name', 'faculty__first_name'],
                'unique_together': {('faculty', 'academic_year')},
            },
        ),
    ]
