# Generated by Django 6.0 on 2026-01-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultysurveydata',
            name='manual_activities_json',
            field=models.JSONField(default=dict, help_text='Manually added activities - never overwritten by import'),
        ),
        migrations.AlterField(
            model_name='facultysurveydata',
            name='activities_json',
            field=models.JSONField(default=dict, help_text='Complete activity data structure from parser (overwrites on import)'),
        ),
    ]
