# Generated by Django 6.0 on 2026-01-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_add_manual_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='division',
            field=models.CharField(blank=True, choices=[('cardiac', 'Cardiac'), ('critical_care', 'Critical Care'), ('multispecialty', 'Multispecialty'), ('pain', 'Pain'), ('transplant', 'Transplant'), ('pediatric', 'Pediatric'), ('surgery', 'Surgery'), ('emergency_medicine', 'Emergency Medicine')], default='', max_length=50),
        ),
    ]
