# Generated by Django 6.0 on 2026-01-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0003_add_division_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='reports_app.activitycategory')),
            ],
            options={
                'verbose_name': 'Activity Goal',
                'verbose_name_plural': 'Activity Goals',
                'ordering': ['category', 'sort_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role/activity name', max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('data_variable', models.CharField(help_text='REDCap data variable name (e.g., CIT_DEPT_GR_HOST)', max_length=100, unique=True)),
                ('base_points', models.IntegerField(default=0, help_text='Base point value')),
                ('modifier_type', models.CharField(choices=[('fixed', 'Fixed Points'), ('count', 'Points × Count'), ('impact_factor', 'Points × Impact Factor')], default='fixed', help_text='How points are calculated', max_length=20)),
                ('max_count', models.PositiveIntegerField(blank=True, help_text='Maximum count for count-based activities (blank = no limit)', null=True)),
                ('max_points', models.PositiveIntegerField(blank=True, help_text='Maximum points cap (blank = no limit)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_departmental', models.BooleanField(default=False, help_text='True if this is tracked by department, not in survey')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types', to='reports_app.activitygoal')),
            ],
            options={
                'verbose_name': 'Activity Type',
                'verbose_name_plural': 'Activity Types',
                'ordering': ['goal__category', 'goal', 'sort_order', 'name'],
            },
        ),
    ]
