# Generated by Django 6.0 on 2026-01-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0004_activity_points_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='is_avc_eligible',
            field=models.BooleanField(default=True, help_text='Include this faculty in AVC point calculations and reports', verbose_name='AVC Eligible'),
        ),
    ]
